/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-08-28 13:49:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addNotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1756388791716L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1756388300864L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Note Taker || Add Notes</title>\r\n");
      out.write("<link href=\"CSS/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"image/NoteTaker2.png\" rel=\"icon\" type=\"image/png\">\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"bg-white shadow-md\">\r\n");
      out.write("	<div class=\"max-w-7xl mx-auto px-4\">\r\n");
      out.write("		<div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Logo -->\r\n");
      out.write("			<div class=\"text-xl font-bold text-blue-600 flex items-center\">\r\n");
      out.write("				<img src=\"image/NoteTaker.png\" alt=\"Note Taker Logo\"\r\n");
      out.write("					style=\"height: 64px;\" class=\"h-12 w-auto\"> Note Taker\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Menu Links -->\r\n");
      out.write("			<div class=\"space-x-6 hidden md:flex\">\r\n");
      out.write("				<a href=\"/NoteTaker\" class=\"text-gray-700 hover:text-blue-600\">Home</a>\r\n");
      out.write("				<a href=\"addNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Add\r\n");
      out.write("					note</a> <a href=\"allNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-700 hover:text-blue-600\">Notes</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Button -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<a href=\"#!\"\r\n");
      out.write("					class=\"px-4 py-2 mx-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700\">\r\n");
      out.write("					Login </a> <a href=\"#!\" data-modal-target=\"default-modal\"\r\n");
      out.write("					data-modal-toggle=\"default-modal\"\r\n");
      out.write("					class=\"px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700\">\r\n");
      out.write("					Register </a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Main modal -->\r\n");
      out.write("<div id=\"default-modal\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("	class=\"hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full\">\r\n");
      out.write("	<div class=\"relative p-4 w-full max-w-2xl max-h-full\">\r\n");
      out.write("		<!-- Modal content -->\r\n");
      out.write("		<div class=\"relative bg-white rounded-lg shadow-sm dark:bg-gray-700\">\r\n");
      out.write("			<!-- Registration Form -->\r\n");
      out.write("			<div class=\"flex items-center justify-center min-h-screen px-4\">\r\n");
      out.write("				<div class=\"bg-white rounded-2xl shadow-lg p-8 w-full max-w-md\">\r\n");
      out.write("					<h2 class=\"text-2xl font-bold text-gray-800 mb-6 text-center\">Create\r\n");
      out.write("						an Account</h2>\r\n");
      out.write("\r\n");
      out.write("					<form action=\"RegisterServlet\" method=\"post\" class=\"space-y-5\">\r\n");
      out.write("						<!-- Full Name -->\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"name\"\r\n");
      out.write("								class=\"block text-sm font-medium text-gray-600 mb-1\">Full\r\n");
      out.write("								Name</label> <input type=\"text\" id=\"name\" name=\"name\"\r\n");
      out.write("								placeholder=\"Enter your full name\"\r\n");
      out.write("								class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Email -->\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"email\"\r\n");
      out.write("								class=\"block text-sm font-medium text-gray-600 mb-1\">Email</label>\r\n");
      out.write("							<input type=\"email\" id=\"email\" name=\"email\"\r\n");
      out.write("								placeholder=\"Enter your email\"\r\n");
      out.write("								class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Password -->\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"password\"\r\n");
      out.write("								class=\"block text-sm font-medium text-gray-600 mb-1\">Password</label>\r\n");
      out.write("							<input type=\"password\" id=\"password\" name=\"password\"\r\n");
      out.write("								placeholder=\"Create a password\"\r\n");
      out.write("								class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Confirm Password -->\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"confirmPassword\"\r\n");
      out.write("								class=\"block text-sm font-medium text-gray-600 mb-1\">Confirm\r\n");
      out.write("								Password</label> <input type=\"password\" id=\"confirmPassword\"\r\n");
      out.write("								name=\"confirmPassword\" placeholder=\"Confirm your password\"\r\n");
      out.write("								class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Submit Button -->\r\n");
      out.write("						<button type=\"submit\"\r\n");
      out.write("							class=\"w-full bg-blue-600 text-white py-2.5 rounded-lg font-medium hover:bg-blue-700 transition shadow-md\">\r\n");
      out.write("							Register</button>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"flex items-center justify-center bg-gray-100\" style=\"height:90vh;\">\r\n");
      out.write("		<form action=\"SaveNote\" method=\"post\" id=\"addForm\" class=\"bg-white p-8 rounded-2xl shadow-lg w-full max-w-md\">\r\n");
      out.write("			<h2 class=\"text-2xl font-semibold text-gray-700 mb-2\">Add Notes</h2>\r\n");
      out.write("\r\n");
      out.write("			<!-- Title Field -->\r\n");
      out.write("			<div class=\"mb-4\">\r\n");
      out.write("				<label for=\"title\" class=\"block text-gray-600 font-medium mb-2\">Title</label>\r\n");
      out.write("				<input type=\"text\" id=\"title\" name=\"title\"\r\n");
      out.write("					class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\"\r\n");
      out.write("					placeholder=\"Enter title\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Content Field -->\r\n");
      out.write("			<div class=\"mb-4\">\r\n");
      out.write("				<label for=\"content\" class=\"block text-gray-600 font-medium mb-2\">Content</label>\r\n");
      out.write("				<textarea id=\"content\" name=\"content\" rows=\"3\"\r\n");
      out.write("					class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\"\r\n");
      out.write("					placeholder=\"Write your content...\"></textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Submit Button -->\r\n");
      out.write("				<button id=\"submitBtn\" type=\"submit\" class=\"focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800\">Add</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("<!-- Clean Light Footer -->\r\n");
      out.write("<footer class=\"bg-gray-50 border-t border-gray-200 mt-16\">\r\n");
      out.write("	<div class=\"max-w-7xl mx-auto px-6 py-12 grid md:grid-cols-4 gap-10\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Brand -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h2 class=\"text-2xl font-bold text-blue-600 mb-3\">NoteTaker</h2>\r\n");
      out.write("			<p class=\"text-gray-600 text-sm\">A simple, modern note-taking app\r\n");
      out.write("				to keep your ideas safe and organized.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Quick Links -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Quick Links</h3>\r\n");
      out.write("			<ul class=\"space-y-2\">\r\n");
      out.write("				<li><a href=\"/NoteTaker\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">Home</a></li>\r\n");
      out.write("				<li><a href=\"allNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">All Notes</a></li>\r\n");
      out.write("				<li><a href=\"addNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">Add Notes</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Resources -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Resources</h3>\r\n");
      out.write("			<ul class=\"space-y-2\">\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Privacy\r\n");
      out.write("						Policy</a></li>\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Terms\r\n");
      out.write("						& Conditions</a></li>\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Help\r\n");
      out.write("						Center</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Social Media -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Follow Us</h3>\r\n");
      out.write("			<div class=\"flex gap-4 text-gray-600 text-xl\">\r\n");
      out.write("				<a href=\"#!\" class=\"hover:text-blue-600\"><i\r\n");
      out.write("					class=\"fab fa-facebook\"></i></a> <a href=\"#!\"\r\n");
      out.write("					class=\"hover:text-blue-600\"><i class=\"fab fa-twitter\"></i></a> <a\r\n");
      out.write("					href=\"#!\" class=\"hover:text-blue-600\"><i\r\n");
      out.write("					class=\"fab fa-instagram\"></i></a> <a href=\"#!\"\r\n");
      out.write("					class=\"hover:text-blue-600\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bottom Bar -->\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"bg-white border-t border-gray-200 py-4 text-center text-sm text-gray-500\">\r\n");
      out.write("		@copyright 2025 NoteTaker Design by Tauseef Khan</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- FontAwesome -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	    $('#addForm').on('submit', function(event){\r\n");
      out.write("	        event.preventDefault(); // this already stops form submission\r\n");
      out.write("            let title = $('#title').val();\r\n");
      out.write("	        let content = $('#content').val();\r\n");
      out.write("	        $('#submitBtn').text='<i class=\"fa fa-cog fa-spin\" style=\"font-size:24px\"></i>'\r\n");
      out.write("	        if(title.trim() === \"\"){\r\n");
      out.write("	        	$('#submitBtn').text=\"Add\"\r\n");
      out.write("	            Swal.fire({\r\n");
      out.write("	                title:\"Please enter the title!\",\r\n");
      out.write("	                icon:\"error\",\r\n");
      out.write("	                draggable:true,\r\n");
      out.write("	            })	\r\n");
      out.write("	        } else if(content.trim() === \"\"){\r\n");
      out.write("	            Swal.fire({\r\n");
      out.write("	                title:\"Please enter the content!\",\r\n");
      out.write("	                icon:\"error\",\r\n");
      out.write("	                draggable:true,\r\n");
      out.write("	            })	\r\n");
      out.write("	            $('#submitBtn').text=\"Add\"\r\n");
      out.write("	        } else {\r\n");
      out.write("	            $.ajax({\r\n");
      out.write("	                url: '");
      out.print(request.getContextPath());
      out.write("/SaveNote',\r\n");
      out.write("	                type: 'POST',\r\n");
      out.write("	                data: {\r\n");
      out.write("	                    title: title,\r\n");
      out.write("	                    content: content\r\n");
      out.write("	                },\r\n");
      out.write("	                success: function(data){\r\n");
      out.write("	                    if(data.trim() === \"true\"){\r\n");
      out.write("	                        Swal.fire({\r\n");
      out.write("	                            title:\"Note Added successfully!\",\r\n");
      out.write("	                            icon:'success',\r\n");
      out.write("	                            draggable:true,\r\n");
      out.write("	                        })	\r\n");
      out.write("	                        $('#submitBtn').text=\"Add\"\r\n");
      out.write("	                        $('#addForm')[0].reset(); // clear form after success\r\n");
      out.write("	                    } else {\r\n");
      out.write("	                    	$('#submitBtn').text=\"Add\"\r\n");
      out.write("	                        Swal.fire({\r\n");
      out.write("	                            title:\"Something went wrong!\",\r\n");
      out.write("	                            icon:\"error\",\r\n");
      out.write("	                        })\r\n");
      out.write("	                    }\r\n");
      out.write("	                },\r\n");
      out.write("	                error: function(xhr){\r\n");
      out.write("	                    Swal.fire({\r\n");
      out.write("	                        title:\"Error: \" + xhr.status,\r\n");
      out.write("	                        icon:\"error\",\r\n");
      out.write("	                        draggable:true,\r\n");
      out.write("	                    })\r\n");
      out.write("	                    $('#submitBtn').text=\"Add\"\r\n");
      out.write("	                }\r\n");
      out.write("	            });\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
