/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-08-28 13:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entities.Note;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import com.helper.FactoryProvider;

public final class allNotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1756389245929L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1756388300864L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.helper.FactoryProvider");
    _jspx_imports_classes.add("com.entities.Note");
    _jspx_imports_classes.add("org.hibernate.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Note Taker || All Notes</title>\r\n");
      out.write("<link href=\"CSS/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"image/NoteTaker2.png\" rel=\"icon\" type=\"image/png\">\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"bg-white shadow-md\">\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4\">\r\n");
      out.write("      <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("        <div class=\"text-xl font-bold text-blue-600 flex items-center\">\r\n");
      out.write("        <img src=\"image/NoteTaker.png\" alt=\"Note Taker Logo\" style=\"height:64px;\" class=\"h-12 w-auto\"> Note Taker</div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Menu Links -->\r\n");
      out.write("        <div class=\"space-x-6 hidden md:flex\">\r\n");
      out.write("          <a href=\"/NoteTaker\" class=\"text-gray-700 hover:text-blue-600\">Home</a>\r\n");
      out.write("          <a href=\"addNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Add note</a>\r\n");
      out.write("          <a href=\"allNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Notes</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Button -->\r\n");
      out.write("        <div>\r\n");
      out.write("          <a href=\"#!\"\r\n");
      out.write("             class=\"px-4 py-2 mx-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700\">\r\n");
      out.write("            Login\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"#!\"\r\n");
      out.write("             class=\"px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700\">\r\n");
      out.write("            Register\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container text-xl font-bold text-blue-600 text-center mt-3\">\r\n");
      out.write("		<h1 class=\"italic\" style=\"font-size:35px;margin:18px;\">All Notes</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"flex flex-wrap gap-4 justify-center container\">\r\n");
      out.write("		");

		Session s = FactoryProvider.getFactory().openSession();
		Query q = s.createQuery("FROM Note ORDER BY addedDate DESC",Note.class);
		List<Note> list = q.list();
		for (Note n : list) {
		
      out.write("\r\n");
      out.write("			 <div class=\"w-80\">\r\n");
      out.write("		        <div class=\"h-48 p-6 bg-white border border-gray-200 rounded-lg shadow-sm \r\n");
      out.write("		                    hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 \r\n");
      out.write("		                    dark:hover:bg-gray-700 flex flex-col justify-between\">\r\n");
      out.write("		            <h5 style=\"font-size:22px;\" class=\"mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white\">\r\n");
      out.write("		                ");
      out.print(n.getTitle() );
      out.write("\r\n");
      out.write("		            </h5>\r\n");
      out.write("		            <p class=\"font-normal text-gray-700 dark:text-gray-400 overflow-hidden\">\r\n");
      out.write("		                ");
      out.print(n.getContent() );
      out.write("\r\n");
      out.write("		            </p>\r\n");
      out.write("		            <div class=\"container text-center text-white\">\r\n");
      out.write("		            	<a href=\"edit.jsp?id=");
      out.print(n.getId());
      out.write("\" class=\"text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700\">\r\n");
      out.write("		            	Edit</a>\r\n");
      out.write("		            	<button onclick=\"DeleteNote(");
      out.print(n.getId());
      out.write(",event)\" class=\"text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700\">\r\n");
      out.write("		            	Delete</button>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("    		</div>\r\n");
      out.write("		");

		}
		s.close();
		
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("<!-- Clean Light Footer -->\r\n");
      out.write("<footer class=\"bg-gray-50 border-t border-gray-200 mt-16\">\r\n");
      out.write("	<div class=\"max-w-7xl mx-auto px-6 py-12 grid md:grid-cols-4 gap-10\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Brand -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h2 class=\"text-2xl font-bold text-blue-600 mb-3\">NoteTaker</h2>\r\n");
      out.write("			<p class=\"text-gray-600 text-sm\">A simple, modern note-taking app\r\n");
      out.write("				to keep your ideas safe and organized.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Quick Links -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Quick Links</h3>\r\n");
      out.write("			<ul class=\"space-y-2\">\r\n");
      out.write("				<li><a href=\"/NoteTaker\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">Home</a></li>\r\n");
      out.write("				<li><a href=\"allNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">All Notes</a></li>\r\n");
      out.write("				<li><a href=\"addNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">Add Notes</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Resources -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Resources</h3>\r\n");
      out.write("			<ul class=\"space-y-2\">\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Privacy\r\n");
      out.write("						Policy</a></li>\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Terms\r\n");
      out.write("						& Conditions</a></li>\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Help\r\n");
      out.write("						Center</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Social Media -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Follow Us</h3>\r\n");
      out.write("			<div class=\"flex gap-4 text-gray-600 text-xl\">\r\n");
      out.write("				<a href=\"#!\" class=\"hover:text-blue-600\"><i\r\n");
      out.write("					class=\"fab fa-facebook\"></i></a> <a href=\"#!\"\r\n");
      out.write("					class=\"hover:text-blue-600\"><i class=\"fab fa-twitter\"></i></a> <a\r\n");
      out.write("					href=\"#!\" class=\"hover:text-blue-600\"><i\r\n");
      out.write("					class=\"fab fa-instagram\"></i></a> <a href=\"#!\"\r\n");
      out.write("					class=\"hover:text-blue-600\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bottom Bar -->\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"bg-white border-t border-gray-200 py-4 text-center text-sm text-gray-500\">\r\n");
      out.write("		@copyright 2025 NoteTaker Design by Tauseef Khan</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- FontAwesome -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		function DeleteNote(id,event){\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:'DeleteServlet',\r\n");
      out.write("				type:'POST',\r\n");
      out.write("				data:{id:id},\r\n");
      out.write("				success:function(data){\r\n");
      out.write("					if(data.trim()==\"true\"){\r\n");
      out.write("						Swal.fire({\r\n");
      out.write("							title:\"Note deleted successfully!\",\r\n");
      out.write("							icon:\"success\",\r\n");
      out.write("							draggable:true,\r\n");
      out.write("						}).then(()=>{\r\n");
      out.write("							window.location.reload();\r\n");
      out.write("						})\r\n");
      out.write("					}else if(data.trim()==\"false\"){\r\n");
      out.write("						Swal.fire(\"Note can't deleted!\");\r\n");
      out.write("					}\r\n");
      out.write("				},error:function(xhr){\r\n");
      out.write("					Swal.fire({\r\n");
      out.write("						title:\"Error: \" + xhr.status,\r\n");
      out.write("						icon:\"error\",\r\n");
      out.write("						draggable:true,\r\n");
      out.write("					})	\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
