/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-08-28 13:19:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entities.Note;
import org.hibernate.Transaction;
import com.helper.FactoryProvider;
import org.hibernate.Session;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1756385441975L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("com.helper.FactoryProvider");
    _jspx_imports_classes.add("com.entities.Note");
    _jspx_imports_classes.add("org.hibernate.Session");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Note Taker || Edit Note</title>\r\n");
      out.write("<link href=\"CSS/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"image/NoteTaker2.png\" rel=\"icon\" type=\"image/png\">\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"bg-white shadow-md\">\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4\">\r\n");
      out.write("      <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("        <div class=\"text-xl font-bold text-blue-600 flex items-center\">\r\n");
      out.write("        <img src=\"image/NoteTaker.png\" alt=\"Note Taker Logo\" style=\"height:64px;\" class=\"h-12 w-auto\"> Note Taker</div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Menu Links -->\r\n");
      out.write("        <div class=\"space-x-6 hidden md:flex\">\r\n");
      out.write("          <a href=\"/NoteTaker\" class=\"text-gray-700 hover:text-blue-600\">Home</a>\r\n");
      out.write("          <a href=\"addNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Add note</a>\r\n");
      out.write("          <a href=\"allNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Notes</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Button -->\r\n");
      out.write("        <div>\r\n");
      out.write("          <a href=\"#\"\r\n");
      out.write("             class=\"px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700\">\r\n");
      out.write("            Login\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");

		int id = Integer.parseInt(request.getParameter("id"));
		Session s = FactoryProvider.getFactory().openSession();
		Transaction tx = s.beginTransaction();
		Note note = (Note) s.get(Note.class, id);
		
      out.write("\r\n");
      out.write("		<div class=\"flex items-center justify-center bg-gray-100\"\r\n");
      out.write("			style=\"height: 90vh;\">\r\n");
      out.write("			<form action=\"UpdateNote\" method=\"post\" id=\"UpdateForm\"\r\n");
      out.write("				class=\"bg-white p-8 rounded-2xl shadow-lg w-full max-w-md\">\r\n");
      out.write("				<h2 class=\"text-2xl font-semibold text-gray-700 mb-2\">Edit the\r\n");
      out.write("					note</h2>\r\n");
      out.write("\r\n");
      out.write("				<!-- Title Field -->\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label for=\"title\" class=\"block text-gray-600 font-medium mb-2\">Title</label>\r\n");
      out.write("					<input type=\"text\" id=\"title\" name=\"title\"\r\n");
      out.write("						class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\"\r\n");
      out.write("						placeholder=\"Enter title\" value=\"");
      out.print(note.getTitle());
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Content Field -->\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label for=\"content\" class=\"block text-gray-600 font-medium mb-2\">Content</label>\r\n");
      out.write("					<textarea id=\"content\" name=\"content\" rows=\"3\"\r\n");
      out.write("						class=\"w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none\"\r\n");
      out.write("						placeholder=\"Write your content...\">");
      out.print(note.getContent());
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Submit Button -->\r\n");
      out.write("				<button id=\"submitBtn\" type=\"submit\"\r\n");
      out.write("					class=\"focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800\">Update</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		s.close();
		
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	    $('#UpdateForm').on('submit', function(event){\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("	 		let title=$('#title').val();\r\n");
      out.write("	 		let content=$('#content').val();\r\n");
      out.write("	 		 if(title.trim() === \"\"){\r\n");
      out.write("		            Swal.fire({\r\n");
      out.write("		                title:\"Please enter the title!\",\r\n");
      out.write("		                icon:\"error\",\r\n");
      out.write("		                draggable:true,\r\n");
      out.write("		            })	\r\n");
      out.write("		        } else if(content.trim() === \"\"){\r\n");
      out.write("		            Swal.fire({\r\n");
      out.write("		                title:\"Please enter the content!\",\r\n");
      out.write("		                icon:\"error\",\r\n");
      out.write("		                draggable:true,\r\n");
      out.write("		            })	\r\n");
      out.write("		        }else{\r\n");
      out.write("					const d={\r\n");
      out.write("						id: \"");
      out.print(note.getId());
      out.write("\",\r\n");
      out.write("						title:title,\r\n");
      out.write("						content:content\r\n");
      out.write("					}\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url:'UpdateNote',\r\n");
      out.write("						type:'POST',\r\n");
      out.write("						data:d,\r\n");
      out.write("						success:function(data){\r\n");
      out.write("							if(data.trim()==\"true\"){\r\n");
      out.write("								Swal.fire({\r\n");
      out.write("									title:\"Note updated successfully!\",\r\n");
      out.write("									icon:\"success\",\r\n");
      out.write("									draggable:true,\r\n");
      out.write("								}).then(()=>{\r\n");
      out.write("									window.location.replace(\"allNotes.jsp\");\r\n");
      out.write("								})\r\n");
      out.write("							}else{\r\n");
      out.write("								Swal.fire({\r\n");
      out.write("									title:\"Something went wrong!\",\r\n");
      out.write("									icon:\"error\",\r\n");
      out.write("									draggable:true\r\n");
      out.write("								});\r\n");
      out.write("							}\r\n");
      out.write("						},\r\n");
      out.write("						error:function(xhr){\r\n");
      out.write("							Swal.fire({\r\n");
      out.write("								title:\"Error :\"+xhr.status,\r\n");
      out.write("								icon:\"error\",\r\n");
      out.write("								draggable:true,\r\n");
      out.write("							});\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("		        }\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
