/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-08-28 13:54:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1756389245929L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1756388300864L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Note Taker || Home Page</title>\r\n");
      out.write("<link href=\"CSS/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"image/NoteTaker2.png\" rel=\"icon\" type=\"image/png\">\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"bg-white shadow-md\">\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4\">\r\n");
      out.write("      <div class=\"flex justify-between items-center h-16\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("        <div class=\"text-xl font-bold text-blue-600 flex items-center\">\r\n");
      out.write("        <img src=\"image/NoteTaker.png\" alt=\"Note Taker Logo\" style=\"height:64px;\" class=\"h-12 w-auto\"> Note Taker</div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Menu Links -->\r\n");
      out.write("        <div class=\"space-x-6 hidden md:flex\">\r\n");
      out.write("          <a href=\"/NoteTaker\" class=\"text-gray-700 hover:text-blue-600\">Home</a>\r\n");
      out.write("          <a href=\"addNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Add note</a>\r\n");
      out.write("          <a href=\"allNotes.jsp\" class=\"text-gray-700 hover:text-blue-600\">Notes</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Button -->\r\n");
      out.write("        <div>\r\n");
      out.write("          <a href=\"#!\"\r\n");
      out.write("             class=\"px-4 py-2 mx-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700\">\r\n");
      out.write("            Login\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"#!\"\r\n");
      out.write("             class=\"px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700\">\r\n");
      out.write("            Register\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		<!-- Hero Section -->\r\n");
      out.write("		<section\r\n");
      out.write("			class=\"max-w-7xl mx-auto px-6 py-20 grid md:grid-cols-2 gap-10 items-center\">\r\n");
      out.write("			<!-- Text -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<h2 class=\"text-5xl font-extrabold text-gray-900 leading-tight mb-6\">\r\n");
      out.write("					Capture Ideas.<br> Stay <span class=\"text-blue-600\">Organized.</span>\r\n");
      out.write("				</h2>\r\n");
      out.write("				<p class=\"text-lg text-gray-600 mb-6\">NoteTaker helps you write,\r\n");
      out.write("					organize, and manage your notes effortlessly. Save your thoughts in\r\n");
      out.write("					one secure place, accessible anytime.</p>\r\n");
      out.write("				<div class=\"flex gap-4\">\r\n");
      out.write("					<a href=\"addNotes.jsp\"\r\n");
      out.write("						class=\"px-6 py-3 bg-blue-600 text-white rounded-xl shadow-md hover:bg-blue-700 transition\">â\r\n");
      out.write("						Create Note</a> <a href=\"allNotes.jsp\"\r\n");
      out.write("						class=\"px-6 py-3 bg-white border border-blue-600 text-blue-600 rounded-xl shadow-md hover:bg-blue-50 transition\">ð\r\n");
      out.write("						View Notes</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Illustration -->\r\n");
      out.write("			<div class=\"flex justify-center\">\r\n");
      out.write("				<img src=\"https://cdn-icons-png.flaticon.com/512/4359/4359963.png\"\r\n");
      out.write("					alt=\"Notes Illustration\" class=\"w-80 md:w-96 drop-shadow-xl\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Features -->\r\n");
      out.write("		<section class=\"bg-white py-16\">\r\n");
      out.write("			<div class=\"max-w-7xl mx-auto px-6 grid md:grid-cols-3 gap-10\">\r\n");
      out.write("				<div class=\"p-6 rounded-2xl shadow-md hover:shadow-xl transition\">\r\n");
      out.write("					<h3 class=\"text-xl font-semibold text-blue-600 mb-2\">ð Quick\r\n");
      out.write("						Notes</h3>\r\n");
      out.write("					<p class=\"text-gray-600\">Write and save notes instantly with a\r\n");
      out.write("						simple and clean interface.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"p-6 rounded-2xl shadow-md hover:shadow-xl transition\">\r\n");
      out.write("					<h3 class=\"text-xl font-semibold text-blue-600 mb-2\">ð Stay\r\n");
      out.write("						Organized</h3>\r\n");
      out.write("					<p class=\"text-gray-600\">Access all your notes in one place,\r\n");
      out.write("						sorted and searchable.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"p-6 rounded-2xl shadow-md hover:shadow-xl transition\">\r\n");
      out.write("					<h3 class=\"text-xl font-semibold text-blue-600 mb-2\">âï¸ Access\r\n");
      out.write("						Anywhere</h3>\r\n");
      out.write("					<p class=\"text-gray-600\">Your notes are always available â\r\n");
      out.write("						whether on desktop or mobile.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container-100\">\r\n");
      out.write("		");
      out.write("<!-- Clean Light Footer -->\r\n");
      out.write("<footer class=\"bg-gray-50 border-t border-gray-200 mt-16\">\r\n");
      out.write("	<div class=\"max-w-7xl mx-auto px-6 py-12 grid md:grid-cols-4 gap-10\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Brand -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h2 class=\"text-2xl font-bold text-blue-600 mb-3\">NoteTaker</h2>\r\n");
      out.write("			<p class=\"text-gray-600 text-sm\">A simple, modern note-taking app\r\n");
      out.write("				to keep your ideas safe and organized.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Quick Links -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Quick Links</h3>\r\n");
      out.write("			<ul class=\"space-y-2\">\r\n");
      out.write("				<li><a href=\"/NoteTaker\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">Home</a></li>\r\n");
      out.write("				<li><a href=\"allNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">All Notes</a></li>\r\n");
      out.write("				<li><a href=\"addNotes.jsp\"\r\n");
      out.write("					class=\"text-gray-600 hover:text-blue-600\">Add Notes</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Resources -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Resources</h3>\r\n");
      out.write("			<ul class=\"space-y-2\">\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Privacy\r\n");
      out.write("						Policy</a></li>\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Terms\r\n");
      out.write("						& Conditions</a></li>\r\n");
      out.write("				<li><a href=\"#!\" class=\"text-gray-600 hover:text-blue-600\">Help\r\n");
      out.write("						Center</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Social Media -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<h3 class=\"text-lg font-semibold text-gray-900 mb-3\">Follow Us</h3>\r\n");
      out.write("			<div class=\"flex gap-4 text-gray-600 text-xl\">\r\n");
      out.write("				<a href=\"#!\" class=\"hover:text-blue-600\"><i\r\n");
      out.write("					class=\"fab fa-facebook\"></i></a> <a href=\"#!\"\r\n");
      out.write("					class=\"hover:text-blue-600\"><i class=\"fab fa-twitter\"></i></a> <a\r\n");
      out.write("					href=\"#!\" class=\"hover:text-blue-600\"><i\r\n");
      out.write("					class=\"fab fa-instagram\"></i></a> <a href=\"#!\"\r\n");
      out.write("					class=\"hover:text-blue-600\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bottom Bar -->\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"bg-white border-t border-gray-200 py-4 text-center text-sm text-gray-500\">\r\n");
      out.write("		@copyright 2025 NoteTaker Design by Tauseef Khan</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- FontAwesome -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
